lib/results_web/router.ex
defmodule ResultsWeb.Router do
  use ResultsWeb, :router

  import ResultsWeb.UserAuth
  import Phoenix.LiveDashboard.Router

  alias ResultsWeb.EnsureRolePlug

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {ResultsWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :user do
    plug EnsureRolePlug, [:admin, :user]
  end

  pipeline :admin do
    plug EnsureRolePlug, :admin
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/api", ResultsWeb do
    pipe_through :api

    scope "/v1" do
      scope "/results" do
        resources("/", ResultController)
      end
    end
  end

  ## Authentication routes

  scope "/", ResultsWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", ResultsWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email

    live "/", ResultLive.Index, :index
    live "/results/:id/edit", ResultLive.Index, :edit

    live "/results/:id", ResultLive.Show, :show
    live "/results/:id/show/edit", ResultLive.Show, :edit
  end

  scope "/", ResultsWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end

  scope "/", ResultsWeb do
    pipe_through [:browser, :require_authenticated_user, :admin]

    live_dashboard "/dashboard", metrics: ResultsWeb.Telemetry, ecto_repos: [Results.Repo]
  end
end

lib/results_web/live/live_helpers.ex
defmodule ResultsWeb.LiveHelpers do
  import Phoenix.LiveView
  import Phoenix.LiveView.Helpers

  alias Results.Accounts
  alias Results.Accounts.User
  alias ResultsWeb.Router.Helpers, as: Routes

  @doc """
  Renders a component inside the `ResultsWeb.ModalComponent` component.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <%= live_modal @socket, ResultsWeb.ResultLive.FormComponent,
        id: @result.id || :new,
        action: @live_action,
        result: @result,
        return_to: Routes.result_index_path(@socket, :index) %>
  """
  def live_modal(socket, component, opts) do
    path = Keyword.fetch!(opts, :return_to)
    modal_opts = [id: :modal, return_to: path, component: component, opts: opts]
    live_component(socket, ResultsWeb.ModalComponent, modal_opts)
  end

  def format_time(time),
    do:
      (time &&
         DateTime.from_unix!(time)
         |> DateTime.shift_zone!("Europe/Moscow")
         |> Timex.format!("{h24}:{m}:{s} {YYYY}-{0M}-{0D}")) || "no time"

  def assign_defaults(session, socket) do
    socket =
      assign_new(socket, :current_user, fn ->
        find_current_user(session)
      end)

    case socket.assigns.current_user do
      %User{} ->
        socket

      _other ->
        socket
        |> put_flash(:error, "You must log in to access this page.")
        |> redirect(to: Routes.user_session_path(socket, :new))
    end
  end

  defp find_current_user(session) do
    with user_token when not is_nil(user_token) <- session["user_token"],
         %User{} = user <- Accounts.get_user_by_session_token(user_token),
         do: user
  end
end

lib/results_web/live/modal_component.ex
defmodule ResultsWeb.ModalComponent do
  use ResultsWeb, :live_component

  @impl true
  def render(assigns) do
    ~L"""
    <div id="<%= @id %>" class="phx-modal"
      phx-capture-click="close"
      phx-window-keydown="close"
      phx-key="escape"
      phx-target="#<%= @id %>"
      phx-page-loading>

      <div class="phx-modal-content">
        <%= live_patch raw("&times;"), to: @return_to, class: "phx-modal-close" %>
        <%= live_component @socket, @component, @opts %>
      </div>
    </div>
    """
  end

  @impl true
  def handle_event("close", _, socket) do
    {:noreply, push_patch(socket, to: socket.assigns.return_to)}
  end
end

lib/results_web/live/result_live/form_component.ex
defmodule ResultsWeb.ResultLive.FormComponent do
  use ResultsWeb, :live_component

  alias Results.Timeline

  @impl true
  def update(%{result: result} = assigns, socket) do
    changeset = Timeline.change_result(result)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event("validate", %{"result" => result_params}, socket) do
    changeset =
      socket.assigns.result
      |> Timeline.change_result(result_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"result" => result_params}, socket) do
    save_result(socket, socket.assigns.action, result_params)
  end

  defp save_result(socket, :edit, result_params) do
    case Timeline.update_result(socket.assigns.result, result_params) do
      {:ok, _result} ->
        {:noreply,
         socket
         |> put_flash(:info, "Result updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_result(socket, :new, result_params) do
    case Timeline.create_result(result_params) do
      {:ok, _result} ->
        {:noreply,
         socket
         |> put_flash(:info, "Result created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/results_web/live/result_live/index.ex
defmodule ResultsWeb.ResultLive.Index do
  use ResultsWeb, :live_view

  alias Results.Timeline

  @impl true
  def mount(_params, session, socket) do
    socket = assign_defaults(session, socket)
    if connected?(socket), do: Timeline.subscribe()

    {:ok, assign(socket, :results, list_results())}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Result")
    |> assign(:result, Timeline.get_result!(id))
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Results")
    |> assign(:result, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    result = Timeline.get_result!(id)
    {:ok, _} = Timeline.delete_result(result)

    {:noreply, assign(socket, :results, list_results())}
  end

  @impl true
  def handle_event("clean", _params, socket) do
    {:ok, _} = Timeline.delete_all_results()

    {:noreply, assign(socket, :results, list_results())}
  end

  @impl true
  def handle_info({:result_created, result}, socket) do
    {:noreply, update(socket, :results, fn results -> [result | results] end)}
  end

  defp list_results do
    Timeline.list_results()
  end
end

lib/results_web/live/result_live/show.ex
defmodule ResultsWeb.ResultLive.Show do
  use ResultsWeb, :live_view

  alias Results.Timeline

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:result, Timeline.get_result!(id))}
  end

  defp page_title(:show), do: "Show Result"
  defp page_title(:edit), do: "Edit Result"
end

lib/results_web/live/result_live/form_component.html.leex
<h2><%= @title %></h2>

<%= f = form_for @changeset, "#",
  id: "result-form",
  phx_target: @myself,
  phx_change: "validate",
  phx_submit: "save" %>

  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= error_tag f, :name %>

  <%= label f, :time %>
  <%= number_input f, :time %>
  <%= error_tag f, :time %>

  <%= submit "Save", phx_disable_with: "Saving..." %>
</form>

lib/results_web/live/result_live/index.html.leex
<h1>Listing Results</h1>

<%= if @live_action in [:new, :edit] do %>
  <%= live_modal @socket, ResultsWeb.ResultLive.FormComponent,
    id: @result.id || :new,
    title: @page_title,
    action: @live_action,
    result: @result,
    return_to: Routes.result_index_path(@socket, :index) %>
<% end %>

<span><%= link "Clean", to: "#", phx_click: "clean", data: [confirm: "Are you sure?"] %></span>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone Time</th>
      <th>Controller Time</th>

      <th></th>
    </tr>
  </thead>
  <tbody id="results">
    <%= for result <- @results do %>
      <tr id="result-<%= result.id %>">
        <td><%= result.name %></td>
        <td><%= format_time(result.phone_time) %></td>
        <td><%= format_time(result.controller_time) %></td>

        <td>
          <span><%= live_redirect "Show", to: Routes.result_show_path(@socket, :show, result) %></span>
          <span><%= live_patch "Edit", to: Routes.result_index_path(@socket, :edit, result) %></span>
          <span><%= link "Delete", to: "#", phx_click: "delete", phx_value_id: result.id, data: [confirm: "Are you sure?"] %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

lib/results_web/live/result_live/show.html.leex
<h1>Show Result</h1>

<%= if @live_action in [:edit] do %>
  <%= live_modal @socket, ResultsWeb.ResultLive.FormComponent,
    id: @result.id,
    title: @page_title,
    action: @live_action,
    result: @result,
    return_to: Routes.result_show_path(@socket, :show, @result) %>
<% end %>

<ul>

  <li>
    <strong>Name:</strong>
    <%= @result.name %>
  </li>

  <li>
    <strong>Phone Time:</strong>
    <%= @result.phone_time %>
  </li>

  <li>
    <strong>Controller Time:</strong>
    <%= @result.controller_time %>
  </li>

</ul>

<span><%= live_patch "Edit", to: Routes.result_show_path(@socket, :edit, @result), class: "button" %></span>
<span><%= live_redirect "Back", to: Routes.result_index_path(@socket, :index) %></span>